baseurl = "https://imlinh.com/"
languageCode = "en-us"
title = "Im Linh"
theme = "hugo-injoker-theme"
googleAnalytics = "UA-75596542-1"
disqusShortname = ""
preserveTaxonomyNames = true
uglyURLs = true
publishDir = "docs"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Linux"
    url = "/tag/linux"
[[menu.main]]
    name = "Python"
    url = "/tag/python"
[[menu.main]]
    name = "Golang"
    url = "/tag/golang"
[[menu.main]]
    name = "TIL"
    url = "/tag/til"
[[menu.main]]
    name = "Linh ba tinh"
    url = "/tag/linh-ba-tinh"

[params]
    description = "Ghi chép linh ba tinh"
    copyright = "© 2017 Im Linh"

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Im Linh"

[Author]
  name = "Tan Linh"
  email = "hi@imlinh.com"
  about = "Mình là Linh - Một thằng cuồng Linux. Đừng ai nhắc đến Windows trước mặt mình nhé. Hehe"
  facebook = "https://facebook.com/tanlinh.nd"
  github = "https://github.com/tanlinhnd"
  twitter = "@tanlinhnd"
  reddit = "https://www.reddit.com/user/tanlinhnd/"
  instagram = "https://www.instagram.com/tanlinhnd/"

[taxonomies]
    tag = "tag"
